name: fifa-champions-old-website
services:
  db:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    volumes:
      - /home/destroflyer/fifa-champions/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      retries: 0
    restart: always
  db-ui:
    image: destrostudios/phpmyadmin
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "1401:443"
    restart: always
  app:
    build:
      dockerfile: app.Dockerfile
    environment:
      DB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      ADMIN_PASSWORD: $ADMIN_PASSWORD
    ports:
      - "127.0.0.1:1403:9000"
    restart: always
